image: Visual Studio 2017

before_build:
- ps: dotnet restore

configuration: Release
build:
  verbosity: minimal

test_script:
  - nunit3-console Gu.Roslyn.Asserts.Tests --result=myresults.xml;format=AppVeyor
  - ps: dotnet test Gu.Roslyn.Asserts.Tests.WithMetadataReferencesAttribute
  - ps: dotnet test Gu.Roslyn.Asserts.XUnit
