image: Visual Studio 2017

before_build:
- ps: dotnet restore

configuration: Release
build:
  verbosity: minimal
  
test_script:
  - ps: dotnet test Gu.Roslyn.Asserts.Tests -c Release --logger:"trx;LogFileName=..\..\Gu.Roslyn.Asserts.Tests.xml"
  - ps: build/uploadtests.ps1 "Gu.Roslyn.Asserts.Tests.xml"
  
