image: Visual Studio 2017

before_build:
- ps: dotnet restore

configuration: Release
build:
  verbosity: minimal

test_script:
- ps: |-
    # run tests
    dotnet test Gu.Roslyn.Asserts.Tests.WithMetadataReferencesAttribute -c Release --logger:"trx;LogFileName=Gu.Roslyn.Asserts.Tests.WithMetadataReferencesAttribute.xml"
    dotnet test Gu.Roslyn.Asserts.XUnit -c Release --logger:"trx;LogFileName=Gu.Roslyn.Asserts.XUnit.xml"
    dotnet test Gu.Roslyn.Asserts.Tests -c Release --logger:"trx;LogFileName=Gu.Roslyn.Asserts.Tests.xml"
    
    # upload results to AppVeyor
    $wc = New-Object 'System.Net.WebClient'
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit3/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\Gu.Roslyn.Asserts.Tests.WithMetadataReferencesAttribute\TestResults\Gu.Roslyn.Asserts.Tests.WithMetadataReferencesAttribute.xml))
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\Gu.Roslyn.Asserts.XUnit\TestResults\Gu.Roslyn.Asserts.XUnit.xml))
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit3/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\Gu.Roslyn.Asserts.Tests\TestResults\Gu.Roslyn.Asserts.Tests.xml))
