namespace Gu.Roslyn.Asserts
{
    /// <summary>
    /// Specifies what diagnostics to allow in the code generated by a code fix.
    /// </summary>
    public enum AllowedDiagnostics
    {
        /// <summary>
        /// Compiler warnings are allowed in the code created by the code fix.
        /// </summary>
        Warnings,

        /// <summary>
        /// No warnings or errors allowed.
        /// </summary>
        None,

        /// <summary>
        /// Compiler warnings and errors are allowed in the code created by the code fix.
        /// </summary>
        WarningsAndErrors
    }
}